### ISSUE TITLE
Install fvtt-token-action-hud-TheWitcherTRPG Error

### ISSUE THREAD

**Issue by Melkkart** [ortegamarcel/fvtt-token-action-hud-thewitchertrpg#3]
Hello I am trying to install the module, following the instructions:
Method 1
In the Foundry VTT configuration screen, go to Additional Modules.
Click on Install module
In the Manifest URL field, paste: https://github.com/ortegamarcel/fvtt-token-action-hud-TheWitcherTRPG/releases/latest/download/module.json
Click Install next to the pasted manifest URL.

but I get this error. (f12 Console info)

setup.js:292 Error: A manifest URL must be provided
    at Module.installPackage (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/dist/packages/views.mjs:1:1425)
    at SetupView.handlePost (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/dist/server/views/setup.mjs:1:1995)
    at Layer.handle [as handle_request] (C:\Program Files\Foundry Virtual Tabletop\resources\app\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Program Files\Foundry Virtual Tabletop\resources\app\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (C:\Program Files\Foundry Virtual Tabletop\resources\app\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (C:\Program Files\Foundry Virtual Tabletop\resources\app\node_modules\express\lib\router\layer.js:95:5)
    at C:\Program Files\Foundry Virtual Tabletop\resources\app\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (C:\Program Files\Foundry Virtual Tabletop\resources\app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\Program Files\Foundry Virtual Tabletop\resources\app\node_modules\express\lib\router\index.js:280:10)
    at file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/dist/server/express.mjs:1:3858

**Comment by ortegamarcel** [comment]
Thanks, for the hint. I released a new version v0.2.1 with the fix. The problem wasn't the code, but the release automation itself.

Please let me know, if it works for you.

**Comment by Melkkart** [comment]
It works, xDD, I'll get to it this afternoon. 
I don't know how to use it, but I don't think it's very difficult.
